name: Deploy S3-Lambda Infrastructure

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        default: "ap-southeast-2"
        required: true
      sourceBucket:
        description: "Source S3 bucket name"
        default: "source-bucket-chien"
        required: true
      destinationBucket:
        description: "Destination S3 bucket name"
        default: "destination-bucket-chien"
        required: true
      lambdaZipBucket:
        description: "S3 bucket to upload Lambda ZIP"
        default: "lambda-function-bucket-chien"
        required: true

env:
  REGION: ${{ github.event.inputs.region }}
  SOURCE_BUCKET: ${{ github.event.inputs.sourceBucket }}
  DEST_BUCKET: ${{ github.event.inputs.destinationBucket }}
  LAMBDA_ZIP_BUCKET: ${{ github.event.inputs.lambdaZipBucket }}
  LAMBDA_ZIP_KEY: lambda_function.zip

jobs:
  upload-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Package Lambda and upload to S3
        run: |
          zip -j lambda_function.zip lambda/transfer.py
          aws s3 cp lambda_function.zip s3://$LAMBDA_ZIP_BUCKET/$LAMBDA_ZIP_KEY

  deploy:
    needs: upload-lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Print input parameters for debugging
        run: |
          echo "Region: $REGION"
          echo "SourceBucket: $SOURCE_BUCKET"
          echo "DestinationBucket: $DEST_BUCKET"
          echo "LambdaS3Bucket: $LAMBDA_ZIP_BUCKET"
          echo "LambdaS3Key: $LAMBDA_ZIP_KEY"

      - name: Deploy CloudFormation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: s3-lambda-transfer
          template: cfn/s3-lambda-transfer.yml
          parameter-overrides: >
            SourceBucketName=${{ env.SOURCE_BUCKET }}
            DestinationBucketName=${{ env.DEST_BUCKET }}
            LambdaS3Bucket=${{ env.LAMBDA_ZIP_BUCKET }}
            LambdaS3Key=${{ env.LAMBDA_ZIP_KEY }}
          capabilities: CAPABILITY_IAM
